### ISSUE TITLE
rive ^0.7.5 incompatible with build_runner ^2.0.1

### ISSUE THREAD

**Issue by mannuch** [rive-app/rive-flutter#93]
`Because build_runner >=2.0.0 depends on graphs ^2.0.0 and rive 0.7.5 depends on graphs ^1.0.0, build_runner >=2.0.0 is incompatible with rive 0.7.5.`

As my project depends on both rive and build_runner, is there any way to update the graphs dependency for rive?

Thank you!

**Comment by WashingtonInoveApps** [comment]
someway ?

**Comment by luigi-rosso** [comment]
It seems like we are compatible with graphs 2.0.0 so we could just update the dependency but would that would require anyone still using graphs 1.0.0 also update to 2.0.0, right @mjohnsullivan?

In the meantime, you can try to point your pubspec to this branch:
```
dependencies:
  rive:
    git:
      url: git@github.com:rive-app/rive-flutter.git
      ref: graphs_2
```
